ci: add commit lint on PR

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,21 @@ jobs:
       if: github.event_name == 'push'
       run: |
         git show -s --format=%s | ./commitlint-0.10.1 lint
+    - name: Commit Lint PR
+      if: github.event_name == 'pull_request'
+      run: |
+        git fetch origin
+        git checkout origin/${{ github.head_ref }}
+        BASE_COMMIT=$(git rev-parse origin/${{ github.base_ref }}~1)
+        git log --pretty=format:"%H" $BASE_COMMIT..HEAD | while read commit_hash; do
+          echo "Linting commit: $commit_hash"
+          git show -s --format=%s "$commit_hash" | ./commitlint-0.10.1 lint
+          if [ $? -ne 0 ]; then
+            echo "::error::Commit linting failed for commit $commit_hash"
+            exit 1
+          fi
+          echo "----------------------------------------"
+        done
   code_lint:
     runs-on: ubuntu-latest
     needs: commit_lint
